<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLxozefn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLxozefn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLxozefn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLxozefn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLxozefn\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Lxozefn',
    'container.build_id' => '7fa86b35',
    'container.build_time' => 1525955321,
));
